"""add ai analysis models

Revision ID: a04f091db3bb
Revises: 557568900c46
Create Date: 2026-09-19 22:14:49.820830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a04f091db3bb'
down_revision: Union[str, Sequence[str], None] = '557568900c46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analysis_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.Enum('PROPERTY', 'UNIT', name='ai_analysis_scope'), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ai_job_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(scope_type = 'PROPERTY' AND property_id IS NOT NULL AND unit_id IS NULL) OR (scope_type = 'UNIT' AND unit_id IS NOT NULL AND property_id IS NULL)", name='ck_ai_job_scope_target'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analysis_jobs_owner_user_id'), 'ai_analysis_jobs', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_ai_analysis_jobs_property_id'), 'ai_analysis_jobs', ['property_id'], unique=False)
    op.create_index(op.f('ix_ai_analysis_jobs_unit_id'), 'ai_analysis_jobs', ['unit_id'], unique=False)
    op.create_table('ai_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('finding', sa.Text(), nullable=False),
    sa.Column('qualification', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ai_analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_insights_job_id'), 'ai_insights', ['job_id'], unique=True)
    op.create_table('ai_insight_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insight_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.Enum('MAINTENANCE', 'EXPENSE', name='ai_evidence_type'), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['insight_id'], ['ai_insights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('insight_id', 'evidence_type', 'evidence_id', name='uq_ai_insight_evidence')
    )
    op.create_index(op.f('ix_ai_insight_evidence_insight_id'), 'ai_insight_evidence', ['insight_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_insight_evidence_insight_id'), table_name='ai_insight_evidence')
    op.drop_table('ai_insight_evidence')
    op.drop_index(op.f('ix_ai_insights_job_id'), table_name='ai_insights')
    op.drop_table('ai_insights')
    op.drop_index(op.f('ix_ai_analysis_jobs_unit_id'), table_name='ai_analysis_jobs')
    op.drop_index(op.f('ix_ai_analysis_jobs_property_id'), table_name='ai_analysis_jobs')
    op.drop_index(op.f('ix_ai_analysis_jobs_owner_user_id'), table_name='ai_analysis_jobs')
    op.drop_table('ai_analysis_jobs')
    # ### end Alembic commands ###
