"""link expenses to maintenance

Revision ID: b977f4a5c553
Revises: cc4c1ecd303c
Create Date: 2026-09-16 10:16:10.584304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b977f4a5c553'
down_revision: Union[str, Sequence[str], None] = 'cc4c1ecd303c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('maintenance_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_expenses_maintenance_id'), 'expenses', ['maintenance_id'], unique=False)
    op.create_foreign_key(None, 'expenses', 'maintenance', ['maintenance_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_maintenance_id'), table_name='expenses')
    op.drop_column('expenses', 'maintenance_id')
    # ### end Alembic commands ###
