"""add tenants and leases

Revision ID: f2c5d2f7b5b6
Revises: ec6a8c9ba2c3
Create Date: 2026-09-15 13:29:28.542765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2c5d2f7b5b6'
down_revision: Union[str, Sequence[str], None] = 'ec6a8c9ba2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('tenant_user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('rent_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', name='lease_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leases_tenant_user_id'), 'leases', ['tenant_user_id'], unique=False)
    op.create_index(op.f('ix_leases_unit_id'), 'leases', ['unit_id'], unique=False)
    op.create_index('uq_active_lease_per_unit', 'leases', ['unit_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_lease_per_unit', table_name='leases', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index(op.f('ix_leases_unit_id'), table_name='leases')
    op.drop_index(op.f('ix_leases_tenant_user_id'), table_name='leases')
    op.drop_table('leases')
    # ### end Alembic commands ###
